service: typescript-lambda-scaffolding

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  minhaFuncao:
    handler: src/infrastructure/lambda/handler.handler
    events:
      - http:
          path: /
          method: any

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
